server:
  port: ${PORT:8762}

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri:  file:/home/oleg/IdeaProjects/config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/